2023-05-14 04:29:24,323 - instabot version: 0.117.0 (bot) - INFO - Instabot version: 0.117.0 Started
2023-05-14 04:29:24,324 - instabot version: 0.117.0 (bot) - DEBUG - Bot imported from A:\MondeVert\venvSD\lib\site-packages\instabot\bot\bot.py
2023-05-14 04:29:39,324 - instabot version: 0.117.0 (api_login) - INFO - Not yet logged in starting: PRE-LOGIN FLOW!
2023-05-14 04:29:39,654 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: accounts/get_prefill_candidates/ returned response: <Response [429]>
2023-05-14 04:29:39,654 - instabot version: 0.117.0 (api) - DEBUG - Responsecode indicates error; response content: b'{"message":"Please wait a few minutes before you try again.","status":"fail"}'
2023-05-14 04:29:39,655 - instabot version: 0.117.0 (api) - ERROR - Request returns 429 error!
2023-05-14 04:29:39,832 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: qe/sync/ returned response: <Response [200]>
2023-05-14 04:29:39,982 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: launcher/sync/ returned response: <Response [200]>
2023-05-14 04:29:40,117 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: accounts/contact_point_prefill/ returned response: <Response [429]>
2023-05-14 04:29:40,117 - instabot version: 0.117.0 (api) - DEBUG - Responsecode indicates error; response content: b'{"message":"Please wait a few minutes before you try again.","status":"fail"}'
2023-05-14 04:29:40,117 - instabot version: 0.117.0 (api) - ERROR - Request returns 429 error!
2023-05-14 04:29:42,509 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: accounts/login/ returned response: <Response [400]>
2023-05-14 04:29:42,509 - instabot version: 0.117.0 (api) - DEBUG - Responsecode indicates error; response content: b'{"message":"challenge_required","challenge":{"url":"https://i.instagram.com/challenge/AXHZK_Aiey5b5a1pcSzWH3X6SSriT1IPVR440DVRqzrsktw59gsRlQa0JtlWJgMBYaSaKy8/AfylH8DtebACcMNsAbhIB1bYmh3iekxsUzNyi1ke4EB9U_sxsPbTdG5Z-ObEynFAT5vK6OKytb9SEg/","api_path":"/challenge/AXHZK_Aiey5b5a1pcSzWH3X6SSriT1IPVR440DVRqzrsktw59gsRlQa0JtlWJgMBYaSaKy8/AfylH8DtebACcMNsAbhIB1bYmh3iekxsUzNyi1ke4EB9U_sxsPbTdG5Z-ObEynFAT5vK6OKytb9SEg/","hide_webview_header":true,"lock":true,"logout":false,"native_flow":true,"flow_render_type":0},"status":"fail","error_type":"checkpoint_challenge_required"}'
2023-05-14 04:29:42,509 - instabot version: 0.117.0 (api) - ERROR - Request returns 400 error!
2023-05-14 04:29:42,509 - instabot version: 0.117.0 (api) - INFO - Instagram's error message: challenge_required
2023-05-14 04:29:42,510 - instabot version: 0.117.0 (api) - INFO - Error type: checkpoint_challenge_required
2023-05-14 04:29:57,525 - instabot version: 0.117.0 (Instagram_Posts) - INFO - ULTIMATE script. Safe to run 24/7!
